version: "2.4"

services:
  dashboard:
    image: "bollegraaf-insight-panel:1.1.2"
    container_name: dashboard
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: db_user
      DB_PASSWORD: db_password
      DB_NAME: BalerDB
      API_PORT: 3001
    ports:
      - "3000:3000"
      - "3001:3001"
    mem_limit: 350m
    mem_reservation: 250m
    networks:
      - proxy-redirect
    volumes:
      - dashboard-data:/data

volumes:
  dashboard-data:

networks:
  proxy-redirect:
    external: true
    name: proxy-redirect